#弹反伤害倍率(以对方伤害为基础)
magnification: 2.5
#惩罚伤害倍率(或者叫破盾?)
punishment: 0.5
#盾上附魔锋利的等级,只有特定等级的盾才能触发弹反,注意是特定,大于或者小于都不可以
enchantedlvl: 4
#血量低的时候显示的tips
tips:
  - "弓箭是没有惩罚伤害的"
  - "弹反对弓箭无駄哒!"
  - "从6hp以上被打到6hp以下时会有音效哦"
  - "按下Alt+F4获得胜利"
  - "只狼道,堂堂连载!"
  - "本插件由ydy爆肝奉献"