#弹反伤害倍率(以对方伤害为基础)
magnification: 2
#弹反范围之内惩罚伤害倍率(或者叫破盾?)
punishment1: 0.2
#弹反范围外到系统格挡范围内惩罚伤害倍率
punishment2: 0.6
#背后惩罚伤害倍率
punishment3: 1.2
#盾上附魔锋利的等级,只有特定等级的盾才能触发弹反,注意是特定,大于或者小于都不可以
enchantedlvl: 4
#弹反范围(mc默认面前180°,我默认面前60°,范围内可触发弹反和punishment1)
angle: 60
#血量低的时候显示的tips
tips:
  - "弓箭也是拥有惩罚伤害的"
  - "格挡时背后被打到会受1.2倍伤害哦"
  - "弹反角度为面前60°范围"
  - "弹反和格挡近战攻击不消耗盾耐久"
  - "保持你的决心!"
  - "胜败乃兵家常事,大侠请重新来过"
  - "不写,懒了"
  - "Hallo world!"
  - "这是一条3.0版本才有的tips!"
  - "你黄了,你蓝了,你白了,你没了"
  - "无事发生"
  - "Tip:Tip:Tip:Tip:Tip:Tip:Tip:"
  - "本游戏不提供人类进化的催化剂"
  - "rm-rf"
  - "弹反对弓箭无駄哒!"
  - "从6hp以上被打到6hp以下时会有音效哦"
  - "按下Alt+F4获得胜利"
  - "只狼道,堂堂连载!"
  - "本插件由ydy爆肝奉献"